# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Needed for backward compatibility
gems: [jekyll-paginate]

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'RGM Haiti Rap Kreyol by Rich Gand Media'
tagline:          'Rap Kreyol Online Radio'
description:      'Rap Kreyol Online Radio by Gandhi'
url:              'http://www.rgmhaiti.com'
baseurl:          ''

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/
- text: Search
  url: /search/


# Author Details
author:         'Abdel Raoof Olakara'

#Social Media links (Use complete URL except for email)
dribbble:
email:
facebook:       'https://www.facebook.com/Richgandmedia'
flickr:
github:         ''
gplus:          ''
instagram:      'https://www.instagram.com/rgmhaiti/'
pinterest:
linkedin:       ''
rss:
stackoverflow:  ''
twitter:        'https://twitter.com/rgmhaiti'

# Google Analytics
gahandler: 'UA-52149651-1'

#if footersvg is 'true' the social media links will be shown top on the copy right in the footer
footersvg: 'true'

# Disqus
disqushandler: 'testingblogo'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.9x beta 2
